name: Backend CI - cargo check

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/backend*'
      - 'backend/**'
      - '!frontend/**'
  pull_request:
    paths:
      - '.github/workflows/backend*'
      - 'backend/**'
      - '!frontend/**'

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./backend

jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          workspaces: backend

      - name: Build
        run: cargo check --all-targets --verbose
